default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: localhost

development:
  <<: *default
  database: e_learning_kazu_development

test:
  <<: *default
  database: e_learning_kazu_test

production:
  <<: *default
  database: e_learning_kazu_production
  username: e_learning_kazu
  password: <%= ENV['E_LEARNING_KAZU_DATABASE_PASSWORD'] %>
  adapter: postgresql
  encoding: unicode
  pool: 5
